version: 2
multi-ecosystem-groups:
  tests:
    commit-message:
      prefix: "chore"
      include: scope
    schedule:
      interval: "daily"
  workflows:
    commit-message:
      prefix: "chore"
      include: scope
    schedule:
      interval: "daily"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "workflows"
    patterns: [ "*" ]
    exclude-paths:
      - .github/workflows/pull-request-automation.yml
      - .github/workflows/pull-request-check-terraform.yml
      - .github/workflows/pull-request-dependabot-automerge.yml
      - .github/workflows/pull-request-label.yml
      - .github/workflows/pull-request-precommit-checks.yml
      - .github/workflows/rebuild-cache-on-merge.yml
      - .github/workflows/release-publish.yml
      - .github/workflows/update-from-skeleton.yml
  - package-ecosystem: "gomod"
    directory: "/"
    multi-ecosystem-group: "tests"
    patterns: [ "*" ]
    cooldown:
      default-days: 14
