name: Automated Approvals

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  automated-approvals:
    name: Automated Approvals
    permissions:
      pull-requests: read
      contents: read
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-automated-approvals.yml@edddecdce4590f94f30d0fdfdf991d8a692fe8dd
    secrets: inherit # pragma: allowlist secret
