name: Automated Approvals

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  automated-approvals:
    name: Automated Approvals
    permissions:
      pull-requests: read
      contents: read
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-automated-approvals.yml@c939591142a230cd8c16784a51f0a9faecf1f4cb
    secrets: inherit # pragma: allowlist secret
