name: Dependabot Auto-Merge

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  dependabot-automerge:
    name: Dependabot Auto-Merge
    permissions:
      contents: write
      pull-requests: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-dependabot-automerge.yml@c939591142a230cd8c16784a51f0a9faecf1f4cb
    secrets: inherit # pragma: allowlist secret
