name: Validate PR Title

on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review, synchronize ]

jobs:
  validate-title:
    name: Validate PR Title
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-conventional-commit-title.yml@c939591142a230cd8c16784a51f0a9faecf1f4cb
