name: Validate PR Title

on:
  pull_request:
    types: [ opened, reopened, edited, ready_for_review, synchronize ]

jobs:
  validate-title:
    name: Validate PR Title
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-pr-conventional-commit-title.yml@edddecdce4590f94f30d0fdfdf991d8a692fe8dd
