name: Rebuild Caches on Merge

on:
  push:
    branches:
      - main
    paths:
      - ".pre-commit-config.yaml"
      - ".tool-versions"
  workflow_dispatch:

jobs:
  pre-commit:
    name: Rebuild Caches
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6

      - id: setup-python
        name: Set up Python 3.14
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          python-version: 3.14

      - id: install-tools
        name: Install Tools with uv
        run: |
          uv tool install pre-commit --with pre-commit-uv

      - id: asdf-install
        name: Setup tools using asdf
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47

      - id: pre-commit
        name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - id: save-pre-commit-cache
        name: Save pre-commit cache
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - id: save-asdf-cache
        name: Save asdf cache
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            ~/.asdf/installs
            ~/.asdf/plugins
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
